<?php
// Conteudo real dos posts, migrado de psimi/blog/

$blog_posts = [
    'equilibrando-os-pratos-da-vida' => [
        'page_title' => 'Equilibrando os pratos da vida | Psicóloga Michely Ciardulo',
        'meta_description' => 'Reflexão sobre a pressão de ser bom demais e como equilibrar as demandas da vida. Freud nos lembra: cada um deve procurar, por si, tornar-se feliz.',
        'h1' => 'Equilibrando os Pratos da Vida',
        'img' => 'img-pratos.webp',
        'data' => '2025-01-15',
        'categoria' => 'Reflexão',
        'blocos' => [
            ['tipo' => 'citacao', 'texto' => '"Nós poderíamos ser muito melhores se não quiséssemos ser tão bons."<br><small>— Sigmund Freud</small>'],
            ['tipo' => 'lead', 'texto' => 'Às vezes sentimos que a vida é um grande malabarismo: trabalho, família, relacionamento, saúde, finanças, lazer... E quando um prato cai, a culpa chega antes mesmo do barulho.'],
            ['tipo' => 'p', 'texto' => 'Vivemos no tempo do Outro. Produzimos para o Outro, nos apresentamos para o Outro, nos avaliamos pelos olhos do Outro. A pressão de ser bom em tudo — bom profissional, bom pai, bom parceiro, boa filha — cria uma demanda impossível de ser atendida.'],
            ['tipo' => 'p', 'texto' => 'Freud nos ensinou que a tentativa de ser perfeito é, paradoxalmente, uma das maiores fontes de adoecimento psíquico. Quando tentamos corresponder a um ideal inatingível, nos afastamos daquilo que realmente somos e do que realmente precisamos.'],
            ['tipo' => 'subtitulo', 'texto' => 'O "adoecimento saudável"'],
            ['tipo' => 'p', 'texto' => 'Existe um momento em que o corpo e a mente dizem "basta". Ansiedade, insônia, irritabilidade, sensação de vazio — são sinais de que os pratos estão pesados demais. E reconhecer isso não é fraqueza: é o primeiro passo para uma reorganização genuína.'],
            ['tipo' => 'subtitulo', 'texto' => 'A psicoterapia como caminho'],
            ['tipo' => 'p', 'texto' => 'Na terapia, não se trata de aprender a segurar mais pratos, mas de entender quais são realmente seus e quais você carrega por obrigação, culpa ou medo. É um espaço para se perguntar: o que EU quero? O que faz sentido para a MINHA vida?'],
            ['tipo' => 'p', 'texto' => '"Cada um deve procurar, por si, tornar-se feliz." — Freud'],
            ['tipo' => 'p', 'texto' => 'Tornar-se feliz não é um destino, é um percurso. E esse percurso passa por aceitar que nem todos os pratos precisam estar girando ao mesmo tempo — e que tudo bem se alguns deles caírem.'],
        ],
    ],
    'quando-o-sofrimento-parece-nao-ter-fim' => [
        'page_title' => 'Quando o sofrimento não tem fim | Psi. Michely Ciardulo',
        'meta_description' => 'Reflexão sobre o mito de Sísifo e a repetição do sofrimento. Por que repetimos padrões dolorosos? Psicóloga Michely Ciardulo explica à luz de Camus e Freud.',
        'h1' => 'Sofrimento Parece Não Ter Fim',
        'img' => 'img-sofrimento.webp',
        'data' => '2025-01-15',
        'categoria' => 'Reflexão',
        'blocos' => [
            ['tipo' => 'lead', 'texto' => 'O mito de Sísifo, interpretado à luz das ideias de Albert Camus e Sigmund Freud, oferece uma perspectiva intrigante sobre como algumas pessoas se encontram aprisionadas aos seus próprios sintomas, repetindo-os incessantemente como Sísifo carrega sua pedra.'],
            ['tipo' => 'p', 'texto' => 'Camus enxerga Sísifo como um símbolo do absurdo da existência, onde a repetição da tarefa reflete a busca incessante por sentido em um mundo aparentemente sem propósito. Analogamente, muitas pessoas parecem presas em um ciclo semelhante, repetindo e mantendo-se ligadas a fontes de sofrimento, como se estivessem carregando suas próprias pedras morro acima, apenas para vê-las rolar de volta.'],
            ['tipo' => 'p', 'texto' => 'Para Freud, a persistência no sofrimento pode ser entendida como uma forma de repetição inconsciente de experiências dolorosas do passado, não elaboradas e aspectos não integrados. Assim como Sísifo retorna repetidamente à sua tarefa, algumas pessoas repetem seus sintomas como uma maneira de lidar com traumas e conteúdos conflituosos.'],
            ['tipo' => 'subtitulo', 'texto' => 'Às vezes o sintoma é tudo que o sujeito possui'],
            ['tipo' => 'p', 'texto' => 'Ao refletirmos sobre o mito de Sísifo, somos convidados a examinar nossa própria relação com o sofrimento e a tarefa árdua e inconsciente de mantê-los em seu exato lugar.'],
            ['tipo' => 'p', 'texto' => 'É possível que ao reconhecermos nossas próprias pedras, possamos encontrar uma maneira possível não de exterminar o sintoma, mas de viver uma vida mais aderente ao que desejamos, às vezes negociando, às vezes elaborando.'],
        ],
    ],
    'terapia-de-casal' => [
        'page_title' => 'Como funciona a terapia de casal? | Psicóloga Michely Ciardulo',
        'meta_description' => 'Como funciona a terapia de casal na psicanálise? Psicóloga Michely Ciardulo explica vínculos afetivos, papéis de gênero e o papel do terapeuta. São Paulo.',
        'h1' => 'Como funciona a Terapia de Casal?',
        'img' => 'img-casal.webp',
        'data' => '2025-01-15',
        'categoria' => 'Artigo',
        'blocos' => [
            ['tipo' => 'lead', 'texto' => 'A terapia de casal se insere como uma ferramenta essencial na jornada de compreensão e fortalecimento dos vínculos afetivos. Neste contexto, mergulhamos nas profundezas da conjugalidade contemporânea, onde as influências familiares, expectativas sociais e dinâmicas inconscientes desempenham papéis fundamentais.'],
            ['tipo' => 'subtitulo', 'texto' => 'Explorando a Responsabilidade na Intimidade Emocional'],
            ['tipo' => 'p', 'texto' => 'Na terapia de casal, os parceiros são convidados a explorar suas responsabilidades na construção e manutenção da intimidade emocional, reconhecendo as influências de gênero e as expectativas sociais associadas (Nunan, 2003).'],
            ['tipo' => 'subtitulo', 'texto' => 'Papéis de Gênero'],
            ['tipo' => 'p', 'texto' => 'Na terapia de casal, os casais são convidados a refletirem sobre questões relacionadas à sensação de perda de liberdade e sobre as diferenças de gênero, de acordo com as construções pessoais e sociais de cada um dos pares (Nunan, 2003).'],
            ['tipo' => 'subtitulo', 'texto' => 'Certezas Efêmeras'],
            ['tipo' => 'p', 'texto' => 'Dentro do contexto terapêutico, os casais são convidados a explorar suas expectativas em relação ao relacionamento, reconhecendo a natureza transitória das certezas e buscando construir uma base mais sólida de confiança mútua.'],
            ['tipo' => 'subtitulo', 'texto' => 'Investigando as Origens Familiares na Conjugalidade'],
            ['tipo' => 'p', 'texto' => 'A terapia de casal proporciona um espaço seguro para a exploração das influências familiares na dinâmica do relacionamento, permitindo que os parceiros compreendam e reconstruam padrões relacionais patológicos e ou adoecidos (McDougall, 1993).'],
            ['tipo' => 'subtitulo', 'texto' => 'Vínculos Inconscientes'],
            ['tipo' => 'p', 'texto' => 'A terapia de casal auxilia os casais a identificarem e explorarem os vínculos inconscientes que moldam suas interações, promovendo uma maior consciência e compreensão mútua de como conteúdos por vezes inconscientes se atualizam na relação (Eiguer, 1984).'],
            ['tipo' => 'subtitulo', 'texto' => 'Colusões e Expectativas Não Expressas'],
            ['tipo' => 'p', 'texto' => 'A terapia de casal abre espaço para a investigação das colusões (acordo secreto) e expectativas não expressas que podem gerar conflitos e ressentimentos, incentivando uma comunicação autêntica e empática entre os parceiros (Willi, 1978).'],
            ['tipo' => 'subtitulo', 'texto' => 'Espaço Transicional'],
            ['tipo' => 'p', 'texto' => 'Durante o processo terapêutico, os casais são encorajados a cultivar um espaço de exploração e crescimento mútuo, onde possam integrar suas realidades internas e externas de forma criativa e enriquecedora (Winnicott, 1971).'],
            ['tipo' => 'subtitulo', 'texto' => 'Transmissão Psíquica Geracional'],
            ['tipo' => 'p', 'texto' => 'A terapia de casal reconhece a importância da transmissão psíquica geracional na construção da identidade e dos padrões relacionais individuais, incentivando os parceiros a explorarem suas heranças familiares e a construírem narrativas mais conscientes e autênticas (Kaës, 1993).'],
            ['tipo' => 'subtitulo', 'texto' => 'O papel transformador da terapia de casal'],
            ['tipo' => 'p', 'texto' => 'A terapia de casal se revela como um espaço de exploração e transformação, onde os parceiros são convidados a navegar nas complexidades de suas relações, reconhecendo e integrando as influências do passado, as expectativas do presente e as aspirações para o futuro. Em meio às tempestades e às calmarias, a terapia de casal pode ser compreendida como uma espécie de farol, vai iluminando junto com o par amoroso, pontos obscuros, proporcionando novas narrativas e formas de se relacionar.'],
            ['tipo' => 'lista', 'itens' => ['<span>A terapia de casal <strong>não é exclusiva para casais casados</strong>; qualquer formato de relacionamento amoroso pode realizar terapia de casal.</span>', '<span>O objetivo da terapia de casal <strong>não é separar nem unir o casal</strong>, mas sim promover uma compreensão mais profunda da relação.</span>', '<span>Assim como na psicoterapia individual, a terapia de casal <strong>não busca direcionar o casal para uma decisão específica</strong>, mas sim explorar as questões subjacentes, insatisfações e queixas do par amoroso.</span>', '<span>Fazer terapia de casal <strong>não é indicativo de uma relação falida</strong>; ao contrário, é um passo corajoso em direção à construção de novos recursos relacionais e conscientização de pontos conflituosos.</span>']],
        ],
    ],
    'estabelecendo-limites' => [
        'page_title' => 'Estabelecendo limites | Psicóloga Michely Ciardulo',
        'meta_description' => 'Estabelecer limites é um ato de amor próprio. Reflexão sobre como validar nossos desejos e afetos nas relações. Por Psicóloga Michely Ciardulo.',
        'h1' => 'Estabelecendo Limites',
        'img' => 'img-limites.webp',
        'data' => '2025-01-15',
        'categoria' => 'Reflexão',
        'blocos' => [
            ['tipo' => 'lead', 'texto' => 'Não podemos controlar como as pessoas irão nos tratar, quanta empatia, amor e respeito iremos receber, mas podemos estabelecer limites sobre o que iremos ou não aceitar.'],
            ['tipo' => 'p', 'texto' => '<strong>Estabelecer limites é uma forma de validarmos nossos desejos e afetos.</strong>'],
            ['tipo' => 'p', 'texto' => 'Podemos estabelecer limites no trabalho, e reconhecer até onde ser solícito com os nossos pares interfere na nossa saúde e sobrecarga de trabalho.'],
            ['tipo' => 'p', 'texto' => 'Podemos estabelecer limites nas relações amorosas e familiares, e procurar reconhecer e estabelecer um limite saudável de entrega para o outro.'],
            ['tipo' => 'p', 'texto' => 'Quando ultrapassamos nossos limites nos colocamos de forma submissa e não autêntica nas relações.'],
            ['tipo' => 'p', 'texto' => 'Muitas pessoas não acolhem seus limites e desejos, com a esperança de ser reconhecido(a), admirado(a) e amado(a), mas na verdade quando não reconhecemos e estabelecemos limites corremos o risco de não sermos tão valorizados e respeitados quanto desejamos, e isso pode desencadear sentimentos de baixa autoestima e frustração.'],
            ['tipo' => 'lista', 'itens' => ['<span><strong>Estabelecer limites é um ato de amor próprio</strong>, de respeito e saúde!</span>']],
        ],
    ],
    'como-voce-tem-lidado-com-seu-tempo' => [
        'page_title' => 'Como você tem lidado com seu tempo? | Psicóloga Michely Ciardulo',
        'meta_description' => 'Reflexão sobre o tempo e nossa relação com ele. Como lidamos com a pressa, a presença e a qualidade das nossas experiências. Por Psicóloga Michely Ciardulo.',
        'h1' => 'Como você tem lidado com seu Tempo?',
        'img' => 'img-tempo.webp',
        'data' => '2025-01-15',
        'categoria' => 'Reflexão',
        'blocos' => [
            ['tipo' => 'lead', 'texto' => 'Há quem diga que o bem mais precioso é o tempo!'],
            ['tipo' => 'p', 'texto' => 'Vivemos tentando a todo custo gerir o tempo, na esperança de termos tempo para fazer mais coisas, muitas vezes sem nem saber quais são.'],
            ['tipo' => 'p', 'texto' => 'Ouvimos música assistindo séries, acompanhando as redes sociais, respondendo uma mensagem no WhatsApp, comendo alguma coisa, e quando falam conosco, respondemos "uhum" ou balançamos a cabeça como quem está prestando atenção em alguma coisa. "Ganha-se" tempo com o acumular das tarefas e não com a qualidade da presença.'],
            ['tipo' => 'p', 'texto' => 'Muitas mães questionam o tão apressado tempo que transforma seu bebê da noite para o dia em uma criança "independente", andando sozinha pela casa.'],
            ['tipo' => 'p', 'texto' => 'Na infância desejamos ser adolescentes. Na adolescência, desejamos apressar o tempo e ter a liberdade de um adulto. Na vida adulta, sentimos saudade de quando éramos crianças, onde tudo parecia ser mais simples.'],
            ['tipo' => 'p', 'texto' => 'Na velhice, gostaríamos de ter mais tempo para as coisas que não tivemos tempo para perceber que eram importantes.'],
            ['tipo' => 'p', 'texto' => 'Estamos sempre insatisfeitos com o apressamento ou a lentidão do tempo. Frequentemente, nos perdemos em suas nuances, alheios à sua natureza fugaz e generosa. Esse tempo, tão valioso, escorre por entre nossos dedos sem que possamos detê-lo.'],
            ['tipo' => 'p', 'texto' => '<strong>Para você, quanto tempo o tempo tem? O que você tem feito com o seu tempo?</strong>'],
        ],
    ],
    'paixao-e-objeto-fantasmatico' => [
        'page_title' => 'Paixão e objeto fantasmático | Psicóloga Michely Ciardulo',
        'meta_description' => 'Reflexão psicanalítica sobre a paixão, idealização e o objeto fantasmático nas relações amorosas. Por Psicóloga Michely Ciardulo em São Paulo, SP.',
        'h1' => 'Paixão e Objeto Fantasmático',
        'img' => 'img-paixao.webp',
        'data' => '2025-01-15',
        'categoria' => 'Reflexão',
        'blocos' => [
            ['tipo' => 'lead', 'texto' => 'O apaixonado projeta no objeto de sua paixão o ego ideal, forjado segundo o modelo onipotente do narcisismo infantil.'],
            ['tipo' => 'p', 'texto' => 'Lembremos que o amor primário é selvagem, quer devorar, possuir, controlar o objeto, negar qualquer diferença. Ao mesmo tempo, a plenitude do narcisismo primário exerce um fascínio, uma atração irresistível.'],
            ['tipo' => 'p', 'texto' => 'Ilusão de plenitude a ser reassegurada em um movimento compulsivo.'],
            ['tipo' => 'p', 'texto' => 'Podemos pensar esse objeto fantasmático como algo ilusório, uma construção atravessada por construções inconscientes e regredidas.'],
            ['tipo' => 'p', 'texto' => 'É esperado que exista uma certa fantasia ao se relacionar com o objeto amoroso e é esperado que isso ocorra. No entanto, os inúmeros desdobramentos da idealização, do fusionamento e das relações com ideal de amor romântico merecem atenção.'],
            ['tipo' => 'subtitulo', 'texto' => 'O ideal de amor romântico'],
            ['tipo' => 'p', 'texto' => 'Existe um amor que irá me "salvar", que dará conta das minhas faltas e que será perfeito. Esse ideal, quando não questionado, pode gerar frustrações intensas e repetições de padrões relacionais adoecidos.'],
        ],
    ],
    'para-ser-dois-e-preciso-ser-um' => [
        'page_title' => 'Para ser dois, é preciso ser um! | Psicóloga Michely Ciardulo',
        'meta_description' => 'Reflexão sobre a importância do autoconhecimento antes de se relacionar. Para ser dois, é preciso primeiro se reconhecer como um. Por Psicóloga Michely Ciardulo.',
        'h1' => 'Para ser dois, é preciso ser Um!',
        'img' => 'img-mulher-feliz.webp',
        'data' => '2025-01-15',
        'categoria' => 'Reflexão',
        'blocos' => [
            ['tipo' => 'lead', 'texto' => 'É preciso nos reconhecer como sujeitos desejantes, singulares e faltantes.'],
            ['tipo' => 'p', 'texto' => 'A relação que temos conosco é extremamente importante e dirá muito sobre como serão nossas relações com outras pessoas.'],
            ['tipo' => 'p', 'texto' => 'Se o sujeito não possui recursos mínimos para se relacionar de forma respeitosa e responsável consigo mesmo, muito provavelmente enfrentará grandes conflitos e angústias na relação com o outro.'],
            ['tipo' => 'p', 'texto' => 'Antes de sermos Dois, precisamos nos reconhecer como UM, validar nossos limites, sonhos, objetivos e história de vida, para então poder somar com o outro e nos tornarmos Dois.'],
            ['tipo' => 'p', 'texto' => 'Talvez pareça um pouco confuso, mas o primeiro relacionamento que devemos construir e estar presentes é o relacionamento conosco mesmos; este é o primeiro passo para poder nos relacionar de forma saudável e prazerosa com um outro fora de nós.'],
        ],
    ],
];
