<?php
// Conteudo real das paginas de especialidade, migrado de psimi/especialidades/

$especialidades_conteudo = [
    'terapia-de-casal' => [
        'page_title' => 'Terapia de Casal | Psicóloga Michely Ciardulo - São Paulo',
        'meta_description' => 'Terapia de casal com a Psicóloga Michely Ciardulo: comunicação, conflitos, ciúmes, confiança e intimidade. Online e presencial em São Paulo. CRP 06/176130.',
        'h1' => 'Relacionamentos, vínculos e terapia de casal',
        'img' => 'thumb01.webp',
        'lead' => 'As relações que construímos também podem revelar conflitos, desejos e lugares que ocupamos diante do outro.',
        'intro_paras' => ['Os relacionamentos fazem parte da nossa história e podem despertar diferentes afetos. Amor, desejo, medo, ciúmes, inseguranças, raiva, necessidade de reconhecimento e medo da perda podem coexistir em uma mesma relação.'],
        'h2' => 'O que pode atravessar os relacionamentos',
        'topicos' => [
            ['titulo' => 'Dependência emocional', 'texto' => 'Quando o medo de perder o outro se torna maior do que a possibilidade de reconhecer os próprios desejos e limites. A necessidade constante de confirmação, o medo de abandono e a dificuldade de estar só podem produzir sofrimento e afetar a forma como os vínculos são construídos.'],
            ['titulo' => 'Limites e desejos', 'texto' => 'Dizer não, sustentar uma escolha ou expressar aquilo que incomoda pode ser difícil quando existe o receio de decepcionar, provocar conflitos ou perder o vínculo. Compreender o próprio lugar na relação também envolve poder reconhecer o que se deseja, e se diferenciar do outro, ou seja, um espaço para ser sujeito para além de ser casal.'],
            ['titulo' => 'Repetições nos relacionamentos', 'texto' => 'Algumas histórias parecem mudar de personagem, mas mantêm determinados conflitos. Relações marcadas pela indisponibilidade afetiva, pelo medo de abandono, pela necessidade de agradar ou por posições que se repetem podem revelar algo que ultrapassa a relação atual.'],
            ['titulo' => 'Família e vínculos', 'texto' => 'Nossa maneira de nos relacionarmos também é atravessada pelas experiências familiares, pelos vínculos construídos ao longo da vida e pelos lugares que aprendemos a ocupar. Essas experiências podem ressurgir, de certa forma, nas relações que estabelecemos na vida adulta.'],
            ['titulo' => 'Expectativas e papéis de gênero', 'texto' => 'As relações também são atravessadas por expectativas sociais sobre o que significa ser mulher ou ser homem. Ideias sobre cuidado, responsabilidade, liberdade, maternidade, casamento e amor podem participar dos conflitos vividos dentro de uma relação. Esses marcadores de gênero muitas vezes dizem respeito às violências vivenciadas por inúmeras mulheres, bem como ao adoecimento e a cobranças extremas, como corpo perfeito, feminilidade e submissão. No masculino, o machismo e o patriarcado também promovem adoecimento, diante de conflitos ligados a performance, virilidade e provimento.'],
            ['titulo' => 'Medo da perda e separação', 'texto' => 'Nem toda dificuldade de se separar está relacionada apenas ao fim de uma relação. Uma separação pode mobilizar afetos de abandono, rejeição, fracasso, solidão e perda de uma história construída em conjunto, e até de identidade.'],
        ],
        'destaques' => [
            'A terapia de casal <strong>não é exclusiva para relações em crise</strong>. Pode ser um cuidado preventivo, voltado a fortalecer a relação e criar novas formas de se relacionar.',
            'O objetivo <strong>não é apontar quem está certo ou errado</strong>, mas ajudar o casal a se compreender e se escutar de outra maneira.',
            'Buscar esse acompanhamento <strong>não é sinal de fracasso</strong>, é uma escolha de cuidado com a relação e com a história construída a dois.',
        ],
        'corpo' => [
            'Nem sempre é fácil compreender o que acontece entre duas pessoas. Às vezes, existe dificuldade para estabelecer limites, expressar desejos, sustentar escolhas ou reconhecer aquilo que se sente. Em outras situações, o medo de perder o outro passa a ocupar um espaço tão grande que a própria pessoa deixa de se escutar.',
            'Na terapia de casal, os dois são convidados a olhar juntos para a dinâmica que construíram: a forma como se comunicam, como lidam com conflitos, ciúmes, confiança e intimidade, e como expectativas de gênero e histórias familiares atravessam o vínculo.',
            'Pode ser um espaço importante em momentos de crise, decisões sobre o futuro da relação, infidelidade, chegada de um filho, ou qualquer transição que mobilize o casal.',
            'Procurar psicoterapia não significa necessariamente querer terminar uma relação ou encontrar uma forma de mantê-la. Pode significar querer compreender o que está acontecendo, o que se repete, o lugar que se ocupa diante do outro e os conflitos que aparecem nesse vínculo.',
        ],
        'cta_titulo' => 'Quando uma relação começa a produzir sofrimento',
        'cta_texto' => 'A psicoterapia pode oferecer um espaço para falar sobre essas questões, seja em casal ou individualmente.',
    ],
    'violencia-domestica' => [
        'page_title' => 'Violência Doméstica | Psicóloga Michely Ciardulo - São Paulo',
        'meta_description' => 'Atendimento psicológico para vítimas de violência doméstica. Acolhimento e suporte terapêutico com Psicóloga Michely Ciardulo. Online e presencial em São Paulo.',
        'h1' => 'Violência Doméstica',
        'img' => 'box-02.webp',
        'lead' => 'A violência doméstica é uma das formas mais devastadoras de sofrimento humano. O atendimento psicológico oferece um espaço seguro de acolhimento, escuta e reconstrução para quem vivencia essa realidade.',
        'intro_paras' => ['A violência doméstica não se limita à agressão física — ela se manifesta também nas formas psicológica, moral, patrimonial e sexual. Muitas vezes, a vítima não reconhece que está sendo violentada, pois a violência é naturalizada no cotidiano da relação.'],
        'h2' => 'Formas de violência doméstica',
        'topicos' => [
            ['titulo' => 'Violência Psicológica', 'texto' => 'Manipulação, humilhação, controle excessivo, ciúmes patológicos, isolamento social e desvalorização constante. Muitas vezes invisível, mas profundamente destrutiva.'],
            ['titulo' => 'Violência Moral', 'texto' => 'Calúnia, difamação e injúria — ataques à reputação e dignidade da vítima perante família, amigos e sociedade.'],
            ['titulo' => 'Violência Física', 'texto' => 'Qualquer ação que cause dano à integridade física, desde empurrões até agressões graves. A violência física frequentemente coexiste com outras formas de violência.'],
            ['titulo' => 'Violência Patrimonial', 'texto' => 'Controle financeiro, destruição de pertences, impedimento de trabalhar — formas de manter a vítima em situação de dependência e submissão.'],
        ],
        'destaques' => [
            '<strong>Você não está sozinha.</strong> Buscar ajuda é um ato de coragem e amor próprio.',
            'A terapia oferece <strong>sigilo absoluto</strong> e um espaço seguro para falar sobre suas experiências.',
            'Central de Atendimento à Mulher: <strong>Ligue 180</strong> (24 horas, gratuito).',
        ],
        'corpo' => [
            'A psicoterapia para vítimas de violência doméstica tem como objetivo oferecer um espaço de acolhimento onde a pessoa possa elaborar suas experiências, reconstruir sua autoestima e desenvolver recursos para romper ciclos de violência.',
            'O trabalho terapêutico ajuda a compreender as dinâmicas que mantêm a pessoa presa nesse ciclo, fortalecendo sua autonomia emocional e capacidade de tomar decisões sobre sua própria vida.',
        ],
        'cta_titulo' => 'Precisa de acolhimento profissional?',
        'cta_texto' => 'Agende uma consulta em um espaço seguro e sigiloso.',
    ],
    'depressao' => [
        'page_title' => 'Depressão | Psicóloga Michely Ciardulo - São Paulo',
        'meta_description' => 'Tratamento psicológico para depressão com Psicóloga Michely Ciardulo. Abordagem psicanalítica, atendimento online e presencial em São Paulo. CRP 06/176130.',
        'h1' => 'Depressão',
        'img' => 'box-03.webp',
        'lead' => 'A depressão vai além da tristeza. É um sofrimento profundo que afeta a forma como a pessoa se relaciona consigo mesma, com os outros e com o mundo. A psicoterapia é fundamental para a compreensão e elaboração desse quadro.',
        'intro_paras' => ['Na perspectiva psicanalítica, a depressão pode ser compreendida como uma resposta a perdas — reais ou simbólicas — que não foram adequadamente elaboradas. O sujeito se retira do mundo, perde o interesse pelas coisas e pelas pessoas, sentindo um vazio que parece não ter explicação.'],
        'h2' => 'Sinais que merecem atenção',
        'topicos' => [
            ['titulo' => 'Tristeza persistente', 'texto' => 'Sentimento de tristeza profunda que não passa, acompanhado de desesperança e sensação de vazio, mesmo sem um motivo aparente.'],
            ['titulo' => 'Alterações no sono e apetite', 'texto' => 'Insônia ou excesso de sono, perda ou aumento significativo de apetite. O corpo também expressa o sofrimento psíquico.'],
            ['titulo' => 'Perda de interesse', 'texto' => 'Desinteresse por atividades que antes eram prazerosas, isolamento social e dificuldade de sentir prazer nas coisas cotidianas.'],
            ['titulo' => 'Dificuldade de concentração', 'texto' => 'Pensamentos negativos recorrentes, dificuldade para tomar decisões, sensação de cansaço mental constante.'],
        ],
        'destaques' => [
            '<strong>Depressão não é frescura.</strong> É um sofrimento real que merece atenção e cuidado profissional.',
            'A terapia pode ser combinada com <strong>acompanhamento psiquiátrico</strong> quando necessário.',
            'O primeiro passo é <strong>pedir ajuda</strong>. Você não precisa enfrentar isso sozinho(a).',
        ],
        'corpo' => [
            'A psicoterapia oferece um espaço para que o sujeito possa falar sobre seu sofrimento, investigar suas causas e construir novas formas de lidar com a dor. O processo terapêutico não busca simplesmente eliminar os sintomas, mas compreender o que eles comunicam.',
            'Através da escuta analítica, é possível acessar conteúdos inconscientes que sustentam o quadro depressivo, abrindo caminho para a elaboração e transformação.',
        ],
        'cta_titulo' => 'Você não precisa sofrer sozinho(a)',
        'cta_texto' => 'Agende uma consulta e dê o primeiro passo em direção ao cuidado.',
    ],
    'morte-e-luto' => [
        'page_title' => 'Morte e Luto | Psicóloga Michely Ciardulo - São Paulo',
        'meta_description' => 'Acompanhamento psicológico para elaboração do luto. Psicóloga Michely Ciardulo oferece acolhimento diante da perda e da finitude. Online e presencial em São Paulo.',
        'h1' => 'Morte e Luto',
        'img' => 'box-04.webp',
        'lead' => 'Há perdas que reorganizam o mundo.',
        'intro_paras' => ['Quando alguém amado morre, não se perde apenas uma pessoa. Perde-se uma presença cotidiana, uma voz familiar, um olhar que reconhecia. Perde-se o lugar à mesa, a conversa habitual, o gesto repetido ao longo dos anos. A cadeira vazia não é apenas um objeto. É a materialidade da ausência.'],
        'h2' => '',
        'topicos' => [
        ],
        'destaques' => [
        ],
        'corpo' => [
            'O luto não é doença. Não é algo a ser curado. Não se cura a saudade de quem se ama.',
            'A perda deixa marcas que permanecem, mesmo quando elaboradas. O amor não termina com a morte. Ele deixa de ter corpo, mas continua inscrito na memória, na história, nos modos de sentir e lembrar.',
            'Há dias em que a ausência se impõe com mais força. Datas, cheiros, músicas reacendem a dor. Isso não significa que o luto falhou. Significa que o vínculo segue existindo sob outra forma.',
            'Elaborar não é apagar. Não é substituir. É, quando possível, permitir uma acomodação da ausência. Não no sentido de torná-la pequena, mas de encontrar um modo de viver sem que a falta paralise completamente o existir.',
            'O luto é uma entre tantas experiências humanas, mas é sempre singular. Não há cronograma. Não há cartilha universal. Mesmo que se fale em etapas, elas não se distribuem da mesma maneira para todos. Nem sempre seguem ordem. Nem sempre se apresentam todas. Nem sempre se encerram.',
            'Há também lutos que não envolvem morte. Lutos por separações, por projetos que não se realizaram, por mudanças abruptas, por versões de si que já não existem. Cada perda exige um trabalho psíquico próprio.',
            'O sofrimento se intensifica quando o entorno exige superação rápida, como se o amor pudesse ser desligado por decisão. O luto não responde à lógica da produtividade. Ele não tem prazo socialmente aceitável.',
            'O que pode haver, ao longo do tempo, é uma reorganização interna. A ausência não desaparece. Ela passa a ocupar outro lugar. A marca permanece. O vínculo se transforma.',
        ],
        'cta_titulo' => 'Precisa de acolhimento nesse momento?',
        'cta_texto' => 'Agende uma consulta em um espaço seguro para falar sobre sua dor.',
    ],
    'ansiedade' => [
        'page_title' => 'Ansiedade, insegurança e autoestima | Psicóloga Michely Ciardulo',
        'meta_description' => 'Psicoterapia para ansiedade, insegurança e autoestima com a Psicóloga Michely Ciardulo. Escuta psicanalítica, online e presencial em São Paulo. CRP 06/176130.',
        'h1' => 'Ansiedade, insegurança e autoestima',
        'img' => 'thumb05.webp',
        'lead' => 'Quando aquilo que acontece por dentro começa a ocupar espaço demais.',
        'intro_paras' => ['A ansiedade pode aparecer quando algo, por dentro, parece estar sempre em movimento. Uma preocupação que não cessa, pensamentos que antecipam diferentes possibilidades, dificuldade para relaxar ou uma sensação de que é preciso estar sempre preparada para o que pode acontecer.'],
        'h2' => 'Quando a ansiedade também fala das relações',
        'topicos' => [
            ['titulo' => 'Como a ansiedade se manifesta', 'texto' => 'Nem sempre existe uma razão evidente para essa inquietação. Às vezes, ela aparece diante de uma situação específica. Em outras, acompanha a rotina, interfere no sono, dificulta a concentração, provoca irritação ou se manifesta no corpo por meio de tensão, aceleração dos pensamentos, aperto no peito, falta de ar, desconfortos gastrointestinais ou dificuldade para descansar.'],
            ['titulo' => 'A necessidade de controlar', 'texto' => 'Também pode existir uma necessidade constante de controlar situações, prever acontecimentos, revisar decisões ou buscar garantias de que tudo ficará bem. A dúvida pode se tornar exaustiva: será que fiz a escolha certa? Será que estou sendo suficiente? Será que a outra pessoa está satisfeita comigo? E se alguma coisa der errado?'],
            ['titulo' => 'O medo diante do outro', 'texto' => 'O medo de ser rejeitada, abandonada ou decepcionar alguém pode fazer com que a pessoa esteja constantemente atenta às reações alheias. Uma mensagem que não foi respondida, uma mudança no comportamento de alguém ou uma situação de conflito podem adquirir uma dimensão difícil de suportar.'],
        ],
        'destaques' => [
        ],
        'corpo' => [
            'Nem toda ansiedade está relacionada apenas ao que pode acontecer. Muitas vezes, ela aparece justamente na relação com o outro.',
            'Pode surgir então a necessidade de agradar, de evitar conflitos, de pedir confirmação, de interpretar cada gesto ou de se adaptar constantemente ao que acredita que o outro espera.',
            'Em alguns casos, a ansiedade se aproxima da insegurança: posso confiar no que sinto? Estou exagerando? Será que tenho razão? Será que sou boa o bastante?',
            'A ansiedade pode estar relacionada à tentativa de antecipar aquilo que ainda não aconteceu, controlar o que não pode ser completamente controlado ou encontrar uma resposta para algo que permanece sem resposta.',
            'Por isso, nem sempre basta identificar o que causa ansiedade. Pode ser importante escutar o que essa ansiedade coloca em movimento, quais conflitos aparecem junto dela, o que está sendo desejado, temido ou evitado e por que determinadas situações assumem um peso tão grande.',
            'Não se trata de encontrar uma explicação única para o sofrimento, mas de construir, pela fala, uma compreensão possível daquilo que está sendo vivido.',
            'A psicoterapia oferece um espaço de escuta para que essas questões possam ser colocadas em palavras e acompanhadas em sua singularidade.',
        ],
        'cta_titulo' => 'Você não precisa chegar sabendo exatamente o que está acontecendo',
        'cta_texto' => 'Na psicoterapia, a fala permite percorrer sua história, seus vínculos, seus conflitos e os sentidos que podem estar presentes naquilo que hoje produz sofrimento.',
    ],
    'inseguranca' => [
        'page_title' => 'Insegurança | Psicóloga Michely Ciardulo - São Paulo',
        'meta_description' => 'A insegurança e o olhar sobre si: psicoterapia de orientação psicanalítica com a Psicóloga Michely Ciardulo. Online e presencial em São Paulo. CRP 06/176130.',
        'h1' => 'Insegurança',
        'img' => 'thumb06.webp',
        'lead' => 'A maneira como uma pessoa se percebe também é atravessada por sua história e por suas relações.',
        'intro_paras' => ['A insegurança pode aparecer como dificuldade para reconhecer os próprios desejos, tomar decisões, sustentar uma escolha ou ocupar determinados lugares. Pode existir uma comparação constante com outras pessoas, uma necessidade de aprovação ou uma sensação de nunca fazer o suficiente.'],
        'h2' => 'Quando algumas histórias parecem se repetir',
        'topicos' => [
        ],
        'destaques' => [
        ],
        'corpo' => [
            'Há situações em que a pessoa percebe que, apesar de tentar fazer diferente, acaba encontrando novamente determinadas experiências.',
            'Relacionamentos que começam de formas parecidas, escolhas que levam aos mesmos conflitos, dificuldade de colocar limites, medo de perder o outro ou uma constante sensação de insuficiência podem indicar que existe algo a ser escutado para além da situação atual.',
            'Nem sempre aquilo que se repete é consciente ou intencional. Muitas vezes, só percebemos a repetição depois que ela já aconteceu algumas vezes.',
            'A psicoterapia pode abrir espaço para perguntar sobre essas repetições e sobre o lugar que cada pessoa ocupa em suas relações, suas escolhas e em sua própria história.',
            'Em alguns casos, a insegurança se aproxima da ansiedade: posso confiar no que sinto? Estou exagerando? Será que tenho razão? Será que sou boa o bastante?',
        ],
        'cta_titulo' => 'Um espaço para escutar o que sustenta a insegurança',
        'cta_texto' => 'Agende uma consulta e encontre um espaço de escuta para essas questões.',
    ],
    'baixa-autoestima' => [
        'page_title' => 'Autoestima | Psicóloga Michely Ciardulo - São Paulo',
        'meta_description' => 'Autoestima para além do pensar positivo: psicoterapia psicanalítica com a Psicóloga Michely Ciardulo. Online e presencial em São Paulo. CRP 06/176130.',
        'h1' => 'Autoestima',
        'img' => 'thumb07.webp',
        'lead' => 'Por trás da baixa autoestima, muitas vezes existe mais do que uma imagem negativa de si.',
        'intro_paras' => ['Pode haver conflitos, experiências de rejeição, cobranças, expectativas e formas de se relacionar que foram sendo construídas ao longo da vida.'],
        'h2' => 'Perguntas que podem ser feitas',
        'topicos' => [
            ['titulo' => 'O peso de reconhecer o próprio valor', 'texto' => 'O que faz com que seja tão difícil reconhecer seu próprio valor? Essa pergunta abre espaço para escutar a história que sustenta a imagem que se tem de si.'],
            ['titulo' => 'A necessidade de corresponder', 'texto' => 'De onde vem a necessidade de corresponder? Nem sempre a exigência que pesa sobre uma pessoa vem de fora: ela também se constrói ao longo dos vínculos.'],
            ['titulo' => 'Quando a confirmação não vem', 'texto' => 'O que acontece quando você não recebe do outro a confirmação que esperava? A resposta a essa ausência costuma dizer muito sobre o lugar ocupado nas relações.'],
        ],
        'destaques' => [
        ],
        'corpo' => [
            'Por isso, olhar para a autoestima não significa simplesmente aprender a pensar positivamente sobre si.',
            'A psicoterapia oferece um espaço de escuta para que essas questões possam ser colocadas em palavras e acompanhadas em sua singularidade.',
        ],
        'cta_titulo' => 'Um espaço para olhar de outro modo para si',
        'cta_texto' => 'Agende uma consulta e comece a percorrer essas questões pela fala.',
    ],
    'dependencia-emocional' => [
        'page_title' => 'Dependência Emocional | Psicóloga Michely Ciardulo - São Paulo',
        'meta_description' => 'Dependência emocional e vínculos: psicoterapia individual com a Psicóloga Michely Ciardulo. Padrões afetivos, limites e medo do abandono. Online e presencial em SP.',
        'h1' => 'Dependência emocional',
        'img' => 'thumb08.webp',
        'lead' => 'A dependência emocional pode aparecer quando a presença, a aprovação ou o reconhecimento do outro parecem se tornar necessários para sustentar a própria vida.',
        'intro_paras' => ['Quando o medo de perder o outro se torna maior do que a possibilidade de reconhecer os próprios desejos e limites. A necessidade constante de confirmação, o medo de abandono e a dificuldade de estar só podem produzir sofrimento e afetar a forma como os vínculos são construídos.'],
        'h2' => 'Psicoterapia individual para relacionamentos',
        'topicos' => [
            ['titulo' => 'Padrões que se repetem', 'texto' => 'Um processo individual pode ajudar a pessoa a compreender melhor seus próprios padrões afetivos: por que certos conflitos se repetem, por que é difícil estabelecer limites, o que a mantém em relações que causam sofrimento, ou como o medo do abandono e a dependência emocional se manifestam na forma de se vincular.'],
            ['titulo' => 'A própria história nos vínculos', 'texto' => 'Esse espaço permite olhar para a própria história, para as experiências familiares e para os lugares que a pessoa aprendeu a ocupar nos vínculos, trazendo mais clareza sobre o que é seu, o que pertence ao outro, e o que pode ser transformado.'],
            ['titulo' => 'Também sem estar em uma relação', 'texto' => 'Pode ser um caminho para quem não está em uma relação e quer entender melhor seus padrões de escolha, ou para quem está enfrentando uma separação e precisa elaborar o que essa perda mobiliza.'],
        ],
        'destaques' => [
        ],
        'corpo' => [
            'Nem sempre é preciso que os dois estejam em terapia para que algo mude na relação.',
            'Nem sempre é fácil compreender o que acontece entre duas pessoas. Às vezes, existe dificuldade para estabelecer limites, expressar desejos, sustentar escolhas ou reconhecer aquilo que se sente. Em outras situações, o medo de perder o outro passa a ocupar um espaço tão grande que a própria pessoa deixa de se escutar.',
            'A psicoterapia pode oferecer um espaço para escutar aquilo que, muitas vezes, aparece nas relações antes mesmo de poder ser compreendido ou colocado em palavras.',
        ],
        'cta_titulo' => 'Um espaço para olhar para os próprios vínculos',
        'cta_texto' => 'Agende uma consulta e comece a percorrer essas questões pela fala.',
    ],
    'burnout' => [
        'page_title' => 'Burnout | Psicóloga Michely Ciardulo - São Paulo',
        'meta_description' => 'Tratamento para Burnout e esgotamento profissional com Psicóloga Michely Ciardulo. Recupere sua qualidade de vida. Atendimento online e presencial em São Paulo.',
        'h1' => 'Burnout',
        'img' => 'box-10.webp',
        'lead' => 'O Burnout — ou Síndrome do Esgotamento Profissional — é muito mais do que "estresse no trabalho". É um estado de exaustão física, emocional e mental causado por uma relação adoecida com o trabalho e suas demandas.',
        'intro_paras' => ['Reconhecido pela OMS como fenômeno ocupacional, o Burnout atinge cada vez mais pessoas que se sentem presas a um ritmo insustentável, muitas vezes sem perceber que estão ultrapassando seus próprios limites há muito tempo.'],
        'h2' => 'Os três pilares do Burnout',
        'topicos' => [
            ['titulo' => 'Exaustão emocional', 'texto' => 'Sensação constante de esgotamento, como se não houvesse mais energia para nada. O cansaço não passa com descanso, porque não é apenas físico — é um esvaziamento profundo do sujeito.'],
            ['titulo' => 'Despersonalização', 'texto' => 'Um distanciamento afetivo das pessoas e do trabalho. Cinismo, irritabilidade, frieza emocional — mecanismos inconscientes de defesa contra um sofrimento que se tornou insuportável.'],
            ['titulo' => 'Redução da realização', 'texto' => 'Sentimento de incompetência, de que nada do que faz é suficiente. A autoestima profissional desmorona, trazendo culpa, frustração e a sensação de ter fracassado.'],
            ['titulo' => 'Insônia e fadiga crônica', 'texto' => 'Dificuldade para dormir mesmo exausto, acordar cansado, sentir que o corpo não recupera. O sono perde sua função reparadora.'],
            ['titulo' => 'Perda de prazer', 'texto' => 'Atividades que antes traziam satisfação perdem o sentido. O trabalho vira obrigação pura, e até o lazer parece um esforço a mais.'],
            ['titulo' => 'Somatizações', 'texto' => 'Dores de cabeça frequentes, problemas gástricos, queda de imunidade, tensão muscular. O corpo carrega o que a mente não consegue processar.'],
        ],
        'destaques' => [
            '<strong>Burnout não é fraqueza.</strong> É o resultado de uma entrega que ultrapassou o limite do suportável.',
            'A terapia ajuda a <strong>compreender os padrões inconscientes</strong> que alimentam o esgotamento.',
            '<strong>Redescobrir o prazer</strong> no trabalho e na vida é possível — com escuta e acolhimento.',
            'Atendimento <strong>online e presencial</strong> para sua comodidade.',
        ],
        'corpo' => [
            'O Burnout não surge de repente — ele se instala silenciosamente, muitas vezes confundido com "fase ruim" ou "falta de força de vontade". Reconhecer os sinais é fundamental:',
            'Para a psicanálise, o Burnout não é apenas uma questão de "trabalhar demais". Ele revela algo mais profundo: a relação que o sujeito estabelece com o ideal — o ideal de produtividade, de perfeição, de ser indispensável.',
            'Muitas vezes, quem adoece por Burnout é justamente quem mais se dedicou, quem mais se cobrou, quem colocou as necessidades dos outros acima das próprias. Há uma dimensão inconsciente nessa entrega excessiva que precisa ser escutada.',
            'A terapia psicanalítica busca compreender: o que está por trás dessa dificuldade de parar? Que mandatos internos empurram o sujeito a ultrapassar seus limites repetidamente? Que angústias se escondem por trás da hiperatividade?',
            'O tratamento do Burnout vai além de técnicas de gerenciamento de estresse. Na psicoterapia, o objetivo é permitir que o sujeito reconheça seus limites, compreenda os padrões que o levaram ao esgotamento e construa uma relação mais saudável consigo mesmo e com o trabalho.',
        ],
        'cta_titulo' => 'Você não precisa continuar se esgotando',
        'cta_texto' => 'Agende uma consulta e comece a reconstruir sua relação com o trabalho e consigo mesmo.',
    ],
    'mudanca-de-carreira' => [
        'page_title' => 'Autoconhecimento | Psicóloga Michely Ciardulo - São Paulo',
        'meta_description' => 'Autoconhecimento na perspectiva psicanalítica. Psicóloga Michely Ciardulo ajuda a reconhecer padrões inconscientes. Atendimento online e presencial em São Paulo.',
        'h1' => 'Autoconhecimento',
        'img' => 'box-09.webp',
        'lead' => 'Autoconhecer-se não é um exercício de autoanálise solitária nem uma busca por uma versão ideal de si mesmo. Também não se trata de alcançar um estado permanente de equilíbrio ou clareza absoluta.',
        'intro_paras' => ['Na perspectiva psicanalítica, o autoconhecimento implica reconhecer que não somos inteiramente transparentes para nós mesmos. Há desejos, fantasias, conflitos e ambivalências que operam para além da consciência imediata. Muitas escolhas que parecem racionais ou "naturais" estão atravessadas por marcas inconscientes, por experiências precoces e por modos de vínculo que foram se estruturando ao longo da vida.'],
        'h2' => '',
        'topicos' => [
        ],
        'destaques' => [
        ],
        'corpo' => [
            'Conhecer-se exige coragem para sustentar perguntas. Perguntas sobre repetições, sobre sofrimentos que retornam, sobre relações que seguem um mesmo roteiro. Não se trata de buscar culpados no passado, mas de compreender como determinadas experiências foram inscritas na história subjetiva e continuam produzindo efeitos.',
            'Na clínica, o autoconhecimento não acontece por meio de técnicas rápidas ou fórmulas motivacionais. Ele se constrói na fala. Ao falar e ser escutado, o sujeito começa a reconhecer sentidos que antes estavam dispersos. Aquilo que era apenas mal-estar pode ganhar nome. Aquilo que parecia destino pode revelar-se como repetição.',
            'Autoconhecer-se não significa controlar tudo o que se sente ou eliminar conflitos internos. Significa ampliar a consciência sobre a própria implicação nas escolhas e nos vínculos. Significa reconhecer limites, assumir responsabilidades e também legitimar desejos.',
            'Esse processo não produz perfeição. Produz maior autenticidade.',
            'E é a partir dessa autenticidade que novas formas de viver e de se relacionar podem se tornar possíveis.',
        ],
        'cta_titulo' => 'Quer redescobrir seu propósito profissional?',
        'cta_texto' => 'Agende uma consulta e dê o primeiro passo em direção a uma carreira que faça sentido.',
    ],
    'solidao-e-conexao-social' => [
        'page_title' => 'Solidão e Conexão Social | Psicóloga Michely Ciardulo - São Paulo',
        'meta_description' => 'Solidão e conexão social: tratamento psicológico com Psicóloga Michely Ciardulo. Isolamento, vínculos e busca por conexão. Online e presencial em São Paulo.',
        'h1' => 'Solidão e Conexão Social',
        'img' => 'img-solidao.webp',
        'lead' => 'A solidão não é simples estado emocional nem fenômeno superficial. É um sinal de que as conexões sociais — que estruturam a vida psíquica — estão fragilizadas ou insuficientes. Embora vivamos em um mundo intensamente conectado digitalmente, muitas pessoas relatam sensação de isolamento profundo.',
        'intro_paras' => ['Segundo a Organização Mundial da Saúde, entre 17% e 21% de indivíduos entre 13 e 29 anos relatam sentir-se sozinhos, com taxas especialmente altas na adolescência. Em países de baixa renda, essa proporção chega a 24%, mais que o dobro das taxas em países de alta renda, em torno de 11%. Esses números mostram que a solidão não é uma experiência isolada, mas um fenômeno de grande escala que afeta tanto jovens quanto adultos em contextos diversos.'],
        'h2' => '',
        'topicos' => [
        ],
        'destaques' => [
        ],
        'corpo' => [
            'A solidão pode emergir mesmo quando há conexão digital ou presença física de outras pessoas. Ela não se limita ao estado de estar só. É uma experiência de ausência de vínculo significativo, de falta de respostas e reconhecimento nos laços sociais.',
            'Estima-se que o isolamento social, que é distinto da solidão — pois envolve ausência de contato social significativo — atinge até 1 em cada 3 idosos e 1 em cada 4 adolescentes. Alguns grupos enfrentam barreiras adicionais à conexão social, como pessoas com deficiência, migrantes, LGBTQ+, povos indígenas e minorias étnicas.',
            'As causas da solidão e do isolamento social são múltiplas e interligadas. Elas incluem problemas de saúde, baixa renda, escolaridade limitada, morar sozinho, infraestrutura comunitária inadequada e políticas públicas insuficientes. A tecnologia digital, quando utilizada sem mediação, também pode intensificar o sentimento de desconexão, especialmente entre jovens que passam grande parte do tempo em interações virtuais que não substituem o vínculo humano.',
            'A solidão não afeta apenas o campo emocional. Tem impacto na saúde física e mental. Pessoas solitárias apresentam maior risco de desenvolver depressão e ansiedade. A solidão também está associada a maiores taxas de doenças cardiovasculares, diabetes, declínio cognitivo e até risco aumentado de morte prematura. Adolescentes que se sentem sozinhos tendem a ter pior desempenho escolar, e adultos podem enfrentar dificuldades maiores para ingressar ou manter empregos e podem ganhar menos ao longo do tempo.',
            'Esses efeitos não se limitam ao indivíduo. A solidão enfraquece a coesão social, compromete a resiliência comunitária e impõe custos econômicos elevados, tanto em perda de produtividade quanto em gastos com saúde.',
            'O relatório da OMS sobre conexão social propõe que a solução para a solidão não está apenas no nível individual, mas também no coletivo: políticas públicas que fortaleçam infraestrutura comunitária, educação que valorize vínculos, espaços sociais que promovam encontros, além de intervenções que reduzam estigmas e promovam conexões verdadeiras.',
            'A solidão, portanto, não é apenas experiência subjetiva. Ela é um fenômeno social e psíquico que toca o sentido de pertencimento, reconhecimento e vínculo. Na clínica, isso se manifesta como sofrimento que não pode ser separado do contexto cultural e relacional no qual o sujeito está inserido.',
            'Reconhecer a solidão como experiência humana intensa e, ao mesmo tempo, como fenômeno de saúde pública abre espaço para uma compreensão mais ampla e ética do sofrimento emocional.',
        ],
        'cta_titulo' => 'Precisa de acolhimento?',
        'cta_texto' => 'Agende uma consulta em um espaço seguro para falar sobre o que sente.',
    ],
];
